id: P1B4B734A
initial_creation_type: input
source_metadata:
  Title: Dhih Journal Vol. 34
  Editor: Samten, Geshe Nawang & Pandey, Janardan
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '2002'
  Āryasāgaranāgarājaparipṛcchā nāma mahāyānasūtram|:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:59:16.945925'
last_modified_at: '2022-03-08T15:59:16.945940'
